# default config.yml
# eggArthropodPercentage is out of 1.0
eggArthropodPercentage: 0.03
eggLootingPercentage: 0.02
eggEntityIDList: [65, 90, 91, 92, 93, 94, 95, 96, 98, 120]
eggDebug: false
eggRemoveDrops: true